# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - tracki-api-pavan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A3D7DAB6C82441459453871A707E52D5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1E7D543FFEA1406E92360C0F424B0B32 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_826CEBC2685A4BD5AD5F5F7A16705BB5 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tracki-api-pavan'
          slot-name: 'Production'
          
          # This is the crucial line that tells Azure to only look in the backend folder.
          # Azure's build system (Oryx) will automatically find your requirements.txt
          # and app.py inside this folder.
          package: ./backend
          